### PR TITLE
Test out shfmt options

### PR DESCRIPTION
**Pull request by Caelink**

### CODE REVIEW

**Comment by Caelink** [comment]
🤔 tool is broke

**Comment by pbrisbin** [comment]
The tool's working correctly, but I gave you a bunk config. I'm sorry, I should've tested it out. The config I gave you passed the options as `["-i 2"]` and not `["-i", "2"]`. It's an easy mistake to make in YAML.

I also forgot a touch of quoting and the fact that ([currently](https://github.com/restyled-io/restyler/commit/7aeed77696cd3526553a3d5c4bda9879cb844938)) you need to keep required arguments, like `-w` for things to work... :man_facepalming: 

This config will work, [this time I tested it](https://github.com/restyled-io/demo/pull/30) :)

```yaml
---
- shfmt:
    arguments:
      - -w
      - -i
      - "2"
      - -ci
```

I think YAML also supports this way, which you may prefer, but I did not test this one:

```yaml
- shfmt:
    arguments: ["-w", "-i", "2", "-ci"]
```

**Comment by Caelink** [comment]
Are you using a fork of shfmt? It doesn't have the option to require a space after the redirect operator `-sr`.

https://github.com/mvdan/sh/blob/cdac70a4704c6c5254913f1d8fdfba652b0022ce/cmd/shfmt/main.go

Edit: Nevermind, that change happened after the latest release, you'd have to point to the repository to get it instead of the go package like you currently do

**Comment by pbrisbin** [comment]
Ah, I see. It's no problem to get it updated (even to the unreleased commit), but I won't be at a computer to do it until probably Monday.

**Comment by Caelink** [comment]
Pretty harmless, kinda fun to have tool, wouldn't mind integrating it. Travis is so slow compared to circleci now that we have docker images going on, I should get around to adding those into travis some time.

**Review by Hazematman — APPROVED** [review]

**Pull request merged**
